// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TrainingProto.proto

package TrainingProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event_Event int32

const (
	Event_UPDATE   Event_Event = 0
	Event_SHUTDOWN Event_Event = 1
)

var Event_Event_name = map[int32]string{
	0: "UPDATE",
	1: "SHUTDOWN",
}
var Event_Event_value = map[string]int32{
	"UPDATE":   0,
	"SHUTDOWN": 1,
}

func (x Event_Event) String() string {
	return proto.EnumName(Event_Event_name, int32(x))
}
func (Event_Event) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_TrainingProto_177f976ca59c0a4b, []int{0, 0}
}

// Represents an event cause by the server.
//
// event describes the resolved Event and data represents the given payload.
type Event struct {
	Event                Event_Event `protobuf:"varint,1,opt,name=event,proto3,enum=Event_Event" json:"event,omitempty"`
	Data                 []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_TrainingProto_177f976ca59c0a4b, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEvent() Event_Event {
	if m != nil {
		return m.Event
	}
	return Event_UPDATE
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Represents a training with all information regarding the training.
//
// stopTime may be 0, if training hasn't finished yet.
type TrainingJob struct {
	ModelId              string   `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	StartTime            int64    `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	StopTime             int64    `protobuf:"varint,3,opt,name=stopTime,proto3" json:"stopTime,omitempty"`
	Running              bool     `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrainingJob) Reset()         { *m = TrainingJob{} }
func (m *TrainingJob) String() string { return proto.CompactTextString(m) }
func (*TrainingJob) ProtoMessage()    {}
func (*TrainingJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_TrainingProto_177f976ca59c0a4b, []int{1}
}
func (m *TrainingJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainingJob.Unmarshal(m, b)
}
func (m *TrainingJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainingJob.Marshal(b, m, deterministic)
}
func (dst *TrainingJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingJob.Merge(dst, src)
}
func (m *TrainingJob) XXX_Size() int {
	return xxx_messageInfo_TrainingJob.Size(m)
}
func (m *TrainingJob) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingJob.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingJob proto.InternalMessageInfo

func (m *TrainingJob) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *TrainingJob) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *TrainingJob) GetStopTime() int64 {
	if m != nil {
		return m.StopTime
	}
	return 0
}

func (m *TrainingJob) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

// Represents a response.
//
// success is true, if the request was processed successfully.
type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_TrainingProto_177f976ca59c0a4b, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*TrainingJob)(nil), "TrainingJob")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterEnum("Event_Event", Event_Event_name, Event_Event_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TrainingProtoClient is the client API for TrainingProto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrainingProtoClient interface {
	// Registers the started training at the server.
	//
	// A Response object with success 'true' is returned, if
	// the training was registered. Otherwise 'false'.
	RegisterTraining(ctx context.Context, in *TrainingJob, opts ...grpc.CallOption) (*Response, error)
	// Updates the started training at the server,
	//
	// A Respone object with responseString 'true' is returned, if the
	// training was updated. Otherwise 'false'.
	UpdateTraining(ctx context.Context, in *TrainingJob, opts ...grpc.CallOption) (*Response, error)
	// Sends the server a request to receive an event-stream.
	// The event stream has orders from the server to the client.
	//
	// A stream of Event is returned.
	ReceiveEvent(ctx context.Context, in *TrainingJob, opts ...grpc.CallOption) (TrainingProto_ReceiveEventClient, error)
}

type trainingProtoClient struct {
	cc *grpc.ClientConn
}

func NewTrainingProtoClient(cc *grpc.ClientConn) TrainingProtoClient {
	return &trainingProtoClient{cc}
}

func (c *trainingProtoClient) RegisterTraining(ctx context.Context, in *TrainingJob, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/TrainingProto/RegisterTraining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingProtoClient) UpdateTraining(ctx context.Context, in *TrainingJob, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/TrainingProto/UpdateTraining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingProtoClient) ReceiveEvent(ctx context.Context, in *TrainingJob, opts ...grpc.CallOption) (TrainingProto_ReceiveEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TrainingProto_serviceDesc.Streams[0], "/TrainingProto/ReceiveEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &trainingProtoReceiveEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TrainingProto_ReceiveEventClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type trainingProtoReceiveEventClient struct {
	grpc.ClientStream
}

func (x *trainingProtoReceiveEventClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TrainingProtoServer is the server API for TrainingProto service.
type TrainingProtoServer interface {
	// Registers the started training at the server.
	//
	// A Response object with success 'true' is returned, if
	// the training was registered. Otherwise 'false'.
	RegisterTraining(context.Context, *TrainingJob) (*Response, error)
	// Updates the started training at the server,
	//
	// A Respone object with responseString 'true' is returned, if the
	// training was updated. Otherwise 'false'.
	UpdateTraining(context.Context, *TrainingJob) (*Response, error)
	// Sends the server a request to receive an event-stream.
	// The event stream has orders from the server to the client.
	//
	// A stream of Event is returned.
	ReceiveEvent(*TrainingJob, TrainingProto_ReceiveEventServer) error
}

func RegisterTrainingProtoServer(s *grpc.Server, srv TrainingProtoServer) {
	s.RegisterService(&_TrainingProto_serviceDesc, srv)
}

func _TrainingProto_RegisterTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainingJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingProtoServer).RegisterTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TrainingProto/RegisterTraining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingProtoServer).RegisterTraining(ctx, req.(*TrainingJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingProto_UpdateTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainingJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingProtoServer).UpdateTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TrainingProto/UpdateTraining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingProtoServer).UpdateTraining(ctx, req.(*TrainingJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingProto_ReceiveEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrainingJob)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrainingProtoServer).ReceiveEvent(m, &trainingProtoReceiveEventServer{stream})
}

type TrainingProto_ReceiveEventServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type trainingProtoReceiveEventServer struct {
	grpc.ServerStream
}

func (x *trainingProtoReceiveEventServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _TrainingProto_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TrainingProto",
	HandlerType: (*TrainingProtoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTraining",
			Handler:    _TrainingProto_RegisterTraining_Handler,
		},
		{
			MethodName: "UpdateTraining",
			Handler:    _TrainingProto_UpdateTraining_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveEvent",
			Handler:       _TrainingProto_ReceiveEvent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "TrainingProto.proto",
}

func init() { proto.RegisterFile("TrainingProto.proto", fileDescriptor_TrainingProto_177f976ca59c0a4b) }

var fileDescriptor_TrainingProto_177f976ca59c0a4b = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xcd, 0xda, 0x36, 0x26, 0x63, 0x2c, 0x61, 0xbc, 0x84, 0xe2, 0x21, 0x2e, 0x1e, 0x02, 0x62,
	0x90, 0xfa, 0x0b, 0x84, 0x16, 0xd4, 0x83, 0x96, 0x35, 0xc1, 0x73, 0x3e, 0x86, 0x12, 0xb0, 0xd9,
	0x90, 0xdd, 0xf6, 0xe2, 0xef, 0xf0, 0xff, 0x4a, 0x36, 0xac, 0xda, 0x9b, 0x97, 0x61, 0xde, 0xbc,
	0xc7, 0x7b, 0xec, 0x5b, 0xb8, 0xc8, 0xfa, 0xa2, 0x69, 0x9b, 0x76, 0xbb, 0xe9, 0xa5, 0x96, 0x69,
	0x37, 0x4c, 0x5e, 0xc2, 0x6c, 0x7d, 0xa0, 0x56, 0x23, 0x87, 0x19, 0x0d, 0x4b, 0xc4, 0x62, 0x96,
	0xcc, 0x97, 0x41, 0x6a, 0xce, 0xe3, 0x14, 0x23, 0x85, 0x08, 0xd3, 0xba, 0xd0, 0x45, 0x74, 0x12,
	0xb3, 0x24, 0x10, 0x66, 0xe7, 0x57, 0xd6, 0x00, 0xc0, 0xcd, 0x37, 0xab, 0x87, 0x6c, 0x1d, 0x3a,
	0x18, 0x80, 0xf7, 0xf6, 0x98, 0x67, 0xab, 0xd7, 0xf7, 0x97, 0x90, 0xf1, 0x4f, 0x38, 0xb3, 0xd1,
	0xcf, 0xb2, 0xc4, 0x08, 0x4e, 0x77, 0xb2, 0xa6, 0x8f, 0xa7, 0xda, 0x64, 0xf9, 0xc2, 0x42, 0xbc,
	0x04, 0x5f, 0xe9, 0xa2, 0xd7, 0x59, 0xb3, 0x23, 0x13, 0x32, 0x11, 0xbf, 0x07, 0x5c, 0x80, 0xa7,
	0xb4, 0xec, 0x0c, 0x39, 0x31, 0xe4, 0x0f, 0x1e, 0x3c, 0xfb, 0x7d, 0x3b, 0x24, 0x44, 0xd3, 0x98,
	0x25, 0x9e, 0xb0, 0x90, 0x5f, 0x83, 0x27, 0x48, 0x75, 0xb2, 0x55, 0x46, 0xa5, 0xf6, 0x55, 0x45,
	0x4a, 0x99, 0x64, 0x4f, 0x58, 0xb8, 0xfc, 0x62, 0x70, 0x7e, 0x54, 0x0f, 0xde, 0x42, 0x28, 0x68,
	0xdb, 0x28, 0x4d, 0xbd, 0x25, 0x30, 0x48, 0xff, 0xbc, 0x63, 0xe1, 0xa7, 0xd6, 0x98, 0x3b, 0x78,
	0x03, 0xf3, 0xbc, 0xab, 0x0b, 0x4d, 0xff, 0x11, 0x27, 0x10, 0x08, 0xaa, 0xa8, 0x39, 0xd0, 0x58,
	0xdd, 0xb1, 0xd4, 0x1d, 0x4b, 0xe7, 0xce, 0x1d, 0x2b, 0x5d, 0xf3, 0x4b, 0xf7, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x36, 0x5c, 0x91, 0x86, 0xbc, 0x01, 0x00, 0x00,
}
