- hosts: nips_training
  vars:
      model_docker_image: "{{ model_docker_image }}"
  remote_user: nips-cloudbuilder
  become: yes
  tasks:
    - name: Pull and start training of model image
      command: docker run -i -t gcr.io/nips-2018-207619/{{ model_docker_image }}