- hosts: nips_training
  vars:
      model_docker_image: "{{ model_docker_image }}"
  remote_user: nips-cloudbuilder
  become: yes
  tasks:
    - name: Add the gcsfuse distribution URL as a package source and import its public key (2)
      shell: echo "deb http://packages.cloud.google.com/apt gcsfuse-xenial main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
    - name: Add the gcsfuse distribution URL as a package source and import its public key (3)
      apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present
    - name: Update repositories cache and install gscfuse package
      apt:
        name: gcsfuse
        update_cache: yes
    - name: Login into GCR Docker Registry
      shell: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
    - name: Add current user to fuse group
      shell: usermod -a -G fuse nips-cloudbuilder
    - name: Make folder for mount
      shell: mkdir /nips-2018-adversarial-vision-challenge-data
    - name: Mount GCS Bucket
      shell: gcsfuse nips-2018-adversarial-vision-challenge-data /nips-2018-adversarial-vision-challenge-data
    - name: Pull and start training of model image
      command: docker run -d -p 6006:6006 -v /nips-2018-adversarial-vision-challenge-data:/nips-2018-adversarial-vision-challenge-data --runtime=nvidia -e MODEL_ID={{ model_docker_image }} -e NVIDIA_VISIBLE_DEVICES=0 gcr.io/nips-2018-207619/{{ model_docker_image }}