- hosts: nips_training
  vars:
      model_docker_image: "{{ model_docker_image }}"
  remote_user: nips-cloudbuilder
  tasks:
    - name: Login into GCR Docker Registry
      shell: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
      become: yes
    - name: Mount GCS Bucket
      shell: gcsfuse nips-2018-adversarial-vision-challenge-data /home/nips-cloudbuilder/nips-2018-adversarial-vision-challenge-data
    - name: Pull and start training of model image
      command: docker run -d -p 6006:6006 --rm --privileged --runtime=nvidia -e MODEL_ID={{ model_docker_image }} -e NVIDIA_VISIBLE_DEVICES=0 gcr.io/nips-2018-207619/{{ model_docker_image }}
      become: yes
