- hosts: nips_training
  vars:
      model_docker_image: "{{ model_docker_image }}"
  remote_user: nips-cloudbuilder
  become: yes
  tasks:
    - name: Retrieve GCP access token
      command: gcloud auth print-access-token
      register: access_token
    - name: Login into GCR Docker Registry
      command: docker login -u oauth2accesstoken -p "{{ access_token.stdout }}" https://gcr.io
    - name: Pull and start training of model image
      command: docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 gcr.io/nips-2018-207619/tiny-imagenet-classifier-model:2602ed5