- hosts: nips_training
  vars:
      model_docker_image: "{{ model_docker_image }}"
  remote_user: nips-cloudbuilder
  become: yes
  tasks:
    - name: Login into GCR Docker Registry
      command: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
    - name: Pull and start training of model image
      command: docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 gcr.io/nips-2018-207619/{{ model_docker_image }}