FROM tensorflow/tensorflow:latest

WORKDIR /opt/app

# load Tiny ImageNet
RUN mkdir ~/.data && \
    cd ~/.data && \
    curl -O http://cs231n.stanford.edu/tiny-imagenet-200.zip && \
    unzip tiny-imagenet-200.zip

# load Python requirements
COPY ./requirements.txt /opt/app
RUN pip install -r requirements.txt

# copy source
COPY . /opt/app

EXPOSE 6006:6006

RUN chmod +x ./start.sh
#CMD ["./start.sh"]
CMD ["python", "./src/main.py"]